# CMake generated Testfile for 
# Source directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib
# Build directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(dynamic "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic")
set_tests_properties(dynamic PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;20;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(cg_atomic_generic_model "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/cg_atomic_generic_model")
set_tests_properties(cg_atomic_generic_model PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;21;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(dynamic_atomic "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic_atomic")
set_tests_properties(dynamic_atomic PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;23;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(dynamic_atomic_2 "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic_atomic_2")
set_tests_properties(dynamic_atomic_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;24;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(dynamic_atomic_3 "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic_atomic_3")
set_tests_properties(dynamic_atomic_3 PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;25;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(dynamic_cond_exp "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic_cond_exp")
set_tests_properties(dynamic_cond_exp PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;26;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(dynamic_forward_reverse "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic_forward_reverse")
set_tests_properties(dynamic_forward_reverse PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;27;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
add_test(dynamic_forward_reverse_2 "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/model/dynamiclib/dynamic_forward_reverse_2")
set_tests_properties(dynamic_forward_reverse_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;28;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/model/dynamiclib/CMakeLists.txt;0;")
