# CMake generated Testfile for 
# Source directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction
# Build directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pantelides "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/pantelides")
set_tests_properties(pantelides PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;19;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(pantelides_flash "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/pantelides_flash")
set_tests_properties(pantelides_flash PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;20;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(soares_secchi "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/soares_secchi")
set_tests_properties(soares_secchi PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;22;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(soares_secchi_flash "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/soares_secchi_flash")
set_tests_properties(soares_secchi_flash PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;23;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(soares_secchi_destil "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/soares_secchi_destil")
set_tests_properties(soares_secchi_destil PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;24;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(dummy_derivative "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/dummy_derivative")
set_tests_properties(dummy_derivative PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;27;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(dummy_derivative_destil "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/dummy_derivative_destil")
set_tests_properties(dummy_derivative_destil PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;28;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
add_test(dummy_derivative_linear "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/dae_index_reduction/dummy_derivative_linear")
set_tests_properties(dummy_derivative_linear PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;29;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/dae_index_reduction/CMakeLists.txt;0;")
