# CMake generated Testfile for 
# Source directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator
# Build directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(evaluator_add "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_add")
set_tests_properties(evaluator_add PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;19;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_cosh "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_cosh")
set_tests_properties(evaluator_cosh PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;20;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_div "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_div")
set_tests_properties(evaluator_div PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;21;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_exp "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_exp")
set_tests_properties(evaluator_exp PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;22;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_log "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_log")
set_tests_properties(evaluator_log PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;23;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_log_10 "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_log_10")
set_tests_properties(evaluator_log_10 PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;24;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_mul "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_mul")
set_tests_properties(evaluator_mul PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;25;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_pow "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_pow")
set_tests_properties(evaluator_pow PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;26;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_sinh "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_sinh")
set_tests_properties(evaluator_sinh PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;27;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_sqrt "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_sqrt")
set_tests_properties(evaluator_sqrt PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;28;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_sub "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_sub")
set_tests_properties(evaluator_sub PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;29;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_tanh "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_tanh")
set_tests_properties(evaluator_tanh PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;30;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
add_test(evaluator_unary "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/evaluator/evaluator_unary")
set_tests_properties(evaluator_unary PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;31;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/evaluator/CMakeLists.txt;0;")
subdirs("adcg")
subdirs("cg")
