# CMake generated Testfile for 
# Source directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns
# Build directory: /home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pattern_matcher "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/pattern_matcher")
set_tests_properties(pattern_matcher PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;19;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(missing_equation "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/missing_equation")
set_tests_properties(missing_equation PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;20;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(cross_iteration "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/cross_iteration")
set_tests_properties(cross_iteration PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;21;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(hessian_with_loops "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/hessian_with_loops")
set_tests_properties(hessian_with_loops PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;22;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(simple_atomic "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/simple_atomic")
set_tests_properties(simple_atomic PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;23;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(simple_atomic_2 "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/simple_atomic_2")
set_tests_properties(simple_atomic_2 PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;24;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(simple_atomic_deploop "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/simple_atomic_deploop")
set_tests_properties(simple_atomic_deploop PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;25;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(plug_flow "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/plug_flow")
set_tests_properties(plug_flow PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;26;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(cstr_collocation "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/cstr_collocation")
set_tests_properties(cstr_collocation PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;27;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
add_test(tank_battery "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/cppadcg-build/test/cppad/cg/patterns/tank_battery")
set_tests_properties(tank_battery PROPERTIES  _BACKTRACE_TRIPLES "/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/CMakeLists.txt;100;ADD_TEST;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;28;add_cppadcg_test;/home/runyu/Documents/GitHub/ti5rcl/Middlewares/CppADCodeGen/test/cppad/cg/patterns/CMakeLists.txt;0;")
